Fix Genesis Block Creation in Sawtooth 1.2
Sawtooth 1.2.3 apparently now requires the consensus algorithm and mode
to be specified. The message showing the regression is:

```
Error: The following setting(s) are required at genesis,
but were not included in the genesis batches:
['sawtooth.consensus.algorithm.name', 'sawtooth.consensus.algorithm.version']
```

Also upgrade to use Sawtooth 1.2 (from 1.1)

Signed-off-by: danintel <daniel.anderson@intel.com>